[project]
name = "robotvoicecontrol"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.7.0",
    "azure-cognitiveservices-speech>=1.43.0",
    "bitsandbytes>=0.45.5",
    "deepface",
    "dotenv>=0.9.9",
    "faiss-cpu>=1.11.0",
    "ffmpeg>=1.4",
    "ffmpeg-python>=0.2.0",
    "google-genai>=1.15.0",
    "langchain>=0.3.25",
    "langchain-community>=0.3.24",
    "langchain-google-genai>=2.1.4",
    "langchain-openai>=0.3.17",
    "langchain-voyageai>=0.1.5",
    "langgraph>=0.4.5",
    "librosa>=0.11.0",
    "numpy",
    "onnxruntime>=1.22.0",
    "py-openshowvar>=1.1.7",
    "pyaudio>=0.2.14",
    "pydub>=0.25.1",
    "silero-vad>=5.1.2",
    "soundfile>=0.13.1",
    "telnetlib3>=2.0.4",
    "tf-keras>=2.19.0",
    "transformers>=4.51.3",
    "ultralytics>=8.3.140",
]

[tool.uv.sources]
deepface = { git = "https://github.com/serengil/deepface.git" }
