FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 16000
CHUNK = 512
MAX_RECORD_SECONDS = 30
SILENCE_THRESHOLD = 4.0
SPEECH_TIMEOUT = 10
WAVE_OUTPUT_FILENAME = "temp_recording.wav"
PROCESSED_AUDIO_FILENAME = "processed_recording.wav"

# === GLOBAL VAD/SPEECH PARAMETERS ===
VAD_THRESHOLD = 0.6
VAD_MIN_SILENCE_DURATION_MS = 5000
VAD_SPEECH_PAD_MS = 500

SPEECH_TIMESTAMP_THRESHOLD = 0.45
SPEECH_TIMESTAMP_MIN_SILENCE_DURATION_MS = 1500
SPEECH_TIMESTAMP_SPEECH_PAD_MS = 500

SPEECH_MIN_DURATION_SECONDS = 1.0  # Minimum duration of detected speech to accept

AUDIO_INT16_NORMALIZATION = 32768.0  # Used to normalize int16 audio to [-1.0, 1.0]
